version: '3'

services:
  bootnode:
    build: ./asset/validator
    command: /usr/local/bin/bootnode --nodekey /asset/validator/bootnode.key
    volumes:
      - ./asset:/asset:ro

  staker:
    build: ./asset/staker
    volumes:
      - ./asset:/asset:ro

  validator-a:
    hostname: A
    build: ./asset/validator
    command: /bin/sh /asset/validator/geth.sh
    env_file: ./envfile
    environment:
      ETHERBASE: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
      PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
    volumes:
      - ./asset:/asset:ro
      - ./data:/data
    ports:
      - 8545:8545/tcp
    depends_on:
      - bootnode

  validator-b:
    hostname: B
    build: ./asset/validator
    command: /bin/sh /asset/validator/geth.sh
    env_file:
      - ./envfile
    environment:
      ETHERBASE: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8'
      PRIVATE_KEY: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
    volumes:
      - ./asset:/asset:ro
      - ./data:/data
    ports:
      - 8546:8545/tcp
    depends_on:
      - bootnode

  validator-c:
    hostname: C
    build: ./asset/validator
    command: /bin/sh /asset/validator/geth.sh
    env_file: ./envfile
    environment:
      ETHERBASE: '0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc'
      PRIVATE_KEY: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'
    volumes:
      - ./asset:/asset:ro
      - ./data:/data
    ports:
      - 8547:8545/tcp
    depends_on:
      - bootnode
